name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Клонуємо репозиторій
        uses: actions/checkout@v4

      - name: Налаштовуємо Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.3"

      - name: Встановлюємо залежності
        run: |
          pip install -r requirements.txt

      - name: Запускаємо тести Django
        run: |
          python manage.py test

  build_and_push:
    needs: test  # Виконається тільки якщо тести пройшли
    runs-on: ubuntu-latest

    steps:
      - name: Клонуємо репозиторій
        uses: actions/checkout@v4

      - name: Логін у Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Збірка та пуш Docker-образу
        run: |
          docker build -t my-django-app .
          docker tag my-django-app mydockerhubuser/my-django-app:latest
          docker push mydockerhubuser/my-django-app:latest
