name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  print-message:
    runs-on: ubuntu-latest

    steps:
      - name: Print a message
        run: echo "Hello, World!"

  build_and_push:
    needs: print-message  # Виконається тільки якщо тести пройшли
    runs-on: ubuntu-latest

    steps:
      - name: Клонуємо репозиторій
        uses: actions/checkout@v4

      - name: Логін у Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Збірка та пуш Docker-образу
        run: |
          docker build -t my-django-app .
          docker tag my-django-app r1man/my-django-app:latest
          docker push r1man/my-django-app:latest
